import { Inter } from 'next/font/google'
import { Providers } from './redux/provider'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Team Ingenious',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
  <html lang="en">
  <head>
  <meta charSet="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <link rel="shortcut icon" type="image/png" href="../assets/images/logos/favicon.png" />
  <link rel="stylesheet" href="../assets/css/styles.min.css" />
      </head>
      <body className={inter.className}>
          <Providers>
            {children}
          </Providers>
        </body>
    </html>
  )
}
